baseURL: "https://ephemeral-raindrop-c5fa88.netlify.app/"
languageCode: en-us
title: MMINT
theme: PaperMod

params:
  homeInfoParams:
    Title: "Welcome to MMINT.UK"
    Content: Portfolio of illustraions, paintings & prints by Artist Rob Green
  socialIcons:
    - name: instagram
      url: "https://www.instagram.com/mmint.uk"
    - name: facebook
      url: "https://www.facebook.com/mmintuk-112376371481073"
    - name: twitter
      url: "https://twitter.com/mmint_uk"     

  cover:
    linkFullImages: false

  Showbreadcrumbs: true

  ShowShareButtons: true

  ShowPostNavLinks: true  

menu:
  main:
    - indentifer: categories
      name: categories
      url: /categories/
      weight: 10
    - indentifer: tags
      name: tags
      url: /tags/
      weight: 20  
      